/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypt;

import java.awt.Color;

import java.util.List;
import java.util.Vector;

/**
 *
 * @author ali
 */
public class A extends javax.swing.JFrame {

    /**
     * Creates new form A
     */
    public A() {
        initComponents();
         this.setSize(970, 660);
        getContentPane().setBackground(Color.black);
       
    }
    
    String lang= " inconnu";
    char []ch={'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};
    int []num={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25};
    List<String>pos=new Vector<>();
    String motfr[]={"un","pour","les","le","la","est","une","non","oui","pour","a","dans","par","de","des","il","elle","ils","elles","nous","vous","on","je","et","etre"};
    String moteng[]={"the","in","of","we","for","an","will","should","is","are","you","he","it","may","be","she","can","could"};
    
    
    
    
    
    
    
    private void decalagefr()
    {String t=E.getText()+' ';int u=1;int cpt=0;
    String ml="",result="";
    while(u<26){
        for(int k=0;k<t.length();k++)
   {  
       boolean tr=false;
       if(t.charAt(k)!=' ' ){
         for(int h=0;h<ch.length;h++){
           if(t.charAt(k)==ch[h])
           {
           ml=ml+ch[(h+u)%26];
           
            
             h=ch.length;
             tr=true;
             
           }
          
          }
         if(tr==false){ml=ml+t.charAt(k);}
         
       }
        
       else {
       
           for (String motfr1 : motfr) {
         
               if(ml.equals(motfr1)) {
               cpt++;
               lang="français";
               }
              
           }
           if(cpt==0) {
               for (String motg : moteng) {
         
               if(ml.equals(motg)) {
               cpt++;
                lang="englais";
               }
              
           }
               
               
               }
           //
         
         result=result+ml+" ";
         ml="";
         lan.setText(lang);
       }
       
      
      
         
        
       
   }
       //System.out.print(result);
         //if(false==tr){
             u=(u+1);pos.add(result);pos.add(String.valueOf(cpt));result="";
         //}
       //else{  pos.add(result);pos.add(String.valueOf(cpt));nat=result;u=26;}
   // System.out.print(String.valueOf(tr)+" "+u+" \n");
      cpt=0;
        
   
    }
    
    int max=Integer.parseInt(pos.get(1));int ii=0;
    for(int p=1;p<pos.size();p=p+2)
    {
     if(Integer.parseInt(pos.get(p))>max)
     {
     max=Integer.parseInt(pos.get(p));
     ii=p-1;
     }
    
    }
  //  pos.stream().forEach(System.out::print);
//        if(!NUM.isVisible())
        S.setText(pos.get(ii));
  /*     else {
               S.setText(pos.get((Integer.parseInt(NUM.getValue().toString())*2)-2 )); 
                }
   */   
       // (n-1)*2
        
         
   
        pos.clear();

  
    
    
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mm = new javax.swing.JLabel();
        lan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        S = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        E = new javax.swing.JTextArea();
        dmr = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        INIT = new javax.swing.JToggleButton();
        lan1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRYPTO");
        setResizable(false);
        getContentPane().setLayout(null);

        mm.setBackground(new java.awt.Color(0, 0, 0));
        mm.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        mm.setForeground(new java.awt.Color(255, 255, 255));
        mm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mm.setText("CRYPTO CESAR");
        mm.setOpaque(true);
        getContentPane().add(mm);
        mm.setBounds(40, 90, 280, 80);

        lan.setBackground(new java.awt.Color(0, 0, 0));
        lan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lan.setForeground(new java.awt.Color(255, 255, 255));
        lan.setText(" inconnu");
        lan.setOpaque(true);
        getContentPane().add(lan);
        lan.setBounds(680, 150, 200, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" TEXT SORTI");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 240, 400, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" TEXT ENTREE");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 390, 30);

        S.setColumns(20);
        S.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        S.setForeground(new java.awt.Color(0, 204, 51));
        S.setRows(5);
        S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 1, true));
        jScrollPane1.setViewportView(S);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 290, 400, 260);

        E.setColumns(20);
        E.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        E.setForeground(new java.awt.Color(255, 51, 0));
        E.setRows(5);
        E.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        E.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(E);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 290, 390, 260);

        dmr.setText("Démarrer");
        dmr.setFocusPainted(false);
        dmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmrActionPerformed(evt);
            }
        });
        dmr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dmrKeyReleased(evt);
            }
        });
        getContentPane().add(dmr);
        dmr.setBounds(40, 560, 390, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crypt/xs.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 40, 307, 164);

        INIT.setText("CLEAR");
        INIT.setDoubleBuffered(true);
        INIT.setFocusPainted(false);
        INIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INITActionPerformed(evt);
            }
        });
        INIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                INITKeyReleased(evt);
            }
        });
        getContentPane().add(INIT);
        INIT.setBounds(510, 560, 400, 30);

        lan1.setBackground(new java.awt.Color(0, 0, 0));
        lan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lan1.setForeground(new java.awt.Color(204, 255, 255));
        lan1.setText(" Langue");
        lan1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));
        lan1.setOpaque(true);
        getContentPane().add(lan1);
        lan1.setBounds(680, 110, 200, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 210, 860, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmrActionPerformed

      
    //    if("Français".equals(lng.getItemAt(lng.getSelectedIndex())))   
        decalagefr();
//else decalageen();
        
// TODO add your handling code here:
    }//GEN-LAST:event_dmrActionPerformed

    private void EKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EKeyTyped
       
    }//GEN-LAST:event_EKeyTyped

    private void EKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EKeyPressed
/*  if( evt.getKeyCode()==KeyEvent.VK_SPACE)
         
     {
         
        
       E.setText(E.getText()+"_");
     }*/        // TODO add your handling code here:
    }//GEN-LAST:event_EKeyPressed

    private void dmrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dmrKeyReleased
         
    }//GEN-LAST:event_dmrKeyReleased

    private void EKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EKeyReleased
 //if(E.getText().length()<16) dmr.setEnabled(false);
   //       else dmr.setEnabled(true);       
    }//GEN-LAST:event_EKeyReleased

    private void INITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INITActionPerformed
       E.setText("");
       S.setText("");
       dmr.setEnabled(false);
       lan.setText(" inconnu");
    }//GEN-LAST:event_INITActionPerformed

    private void INITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_INITKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_INITKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new A().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea E;
    private javax.swing.JToggleButton INIT;
    private javax.swing.JTextArea S;
    private javax.swing.JToggleButton dmr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lan;
    private javax.swing.JLabel lan1;
    private javax.swing.JLabel mm;
    // End of variables declaration//GEN-END:variables
}
